version: "3.9"

services: 
  app: 
    container_name: "NodeApp"
    build: .
    restart: "always"
    ports: 
      - 3000:3000
    environment:
      PASSWORD: postgres
      USER: postgres
      DB: db_test
  db:
    container_name: "database"
    image: postgres:latest
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db_test